- src/neo2/ExpressNodeRpcPlugin.cs
Adds a custom RPC endpoint for neo-express to enable [visual devtracker](https://github.com/neo-project/neo-visual-tracker/) to retrieve a list of non-empty blocks quickly. Needed for [visual devtracker bug 16](https://github.com/neo-project/neo-visual-tracker/issues/16)
Fixes #16
> Add express-get-populated-blocks RPC endpoint

- src/abstractions/Models/ExpressConsensusNode.cs
- src/neo2/BlockchainOperations.cs
fixes #7 
With this change:
* new neo-express instances will not write out a debug-port value for their consensus nodes
* existing neo-express instances will maintain a non-zero debug-port value in their consensus nodes when updating the json file in any way (for example, creating a new wallet)
* existing neo-express instances with a zero debug-port value in their consensus nodes will remove the debug-port property entirely when updating the json file in any way (for example, creating a new wallet)
> mark debug port as DefaultValueHandling.Ignore 

- src/neo-express/Commands/ContractCommand.Deploy.cs
- src/neo-express/Extensions.cs
- src/neo-express/Models/AbiContract.cs
This PR updates neo-express to read the contract metadata that has [recently been added](https://github.com/neo-project/neo-devpack-dotnet/pull/148) to neon. Will still query user if storage and/or dynamic invoke info is missing from abi.json file (for example, if the user is using an earlier version of neon or neon-de). 
Also adds an --overwrite flag to avoid prompting the user when when deploying a contract that has previously been deployed with the same name but different contract hash
> read metadata from .abi.json

- src/neo-express/Node/ExpressNodeRpcPlugin.cs
instead of getting all the populated blocks in a single call, modify get-populated-blocks to take count and start parameters to specify how the maximum number of blocks to retrieve and what block index to start from 
fixes #35
> add count and start parameters to get-populated-blocks

- src/neo-express/BlockchainOperations.cs
- src/neo-express/Commands/RunCommand.cs
- src/neo-express/Node/ExpressNodeRpcPlugin.cs
- src/neo-express/Node/NodeUtility.cs
This PR adds a --preload-gas support that will add enough blocks after the genesis block to give the genesis account the specified amount of gas. Note, the gas will be unavailable to start - the user will still needs to execute a transfer to release the GAS for claiming. 
Question for reviewers: Should we cap the amount of gas / blocks the user can specify? On my dev box, it takes about a second to add 200 blocks, which creates 1600 GAS. If we cap at 10 seconds (on my machine) that's around 2,000 blocks / 16,000 GAS
fixes #40
> Add GAS preload support

- src/neo-express/BlockchainOperations.cs
- src/neo-express/Commands/ClaimCommand.cs
- src/neo-express/Commands/ContractCommand.Deploy.cs
- src/neo-express/Commands/ShowCommand.Transaction.cs
- src/neo-express/Commands/ShowCommand.cs
- src/neo-express/Commands/TransferCommand.cs
- src/neo-express/Models/ClaimableTransaction.cs
- src/neo-express/Models/UnspentTransaction.cs
- src/neo-express/NeoRpcClient.cs
- src/neo-express/Node/ExpressNodeRpcPlugin.cs
- src/neo-express/RpcTransactionManager.cs
- src/neo-express/launch.ps1
When I originally built neo-express, I used neo-cli as a guide. However, since neo-express is split into separate processes, I built [custom RPC endpoints](https://github.com/neo-project/neo-express/blob/80c500f2aad7da9651b53fafea6f34e027d08646/src/neo-express/Node/ExpressNodeRpcPlugin.cs#L477) to allow the CLI to invoke transfer/claim/deploy/invoke. However, the more common way to accomplish these tasks is to build the transaction on the client side (including signing) and submitting via [`sendrawtransaction`](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/sendrawtransaction.html).
This PR updates `transfer`, `claim` and `contract deploy` commands to use `sendrawtransaction` RPC endpoints rather than the neo-express custom endpoints described above. Support for using …
> Use sendRawTransaction RPC endpoint for transfer, claim and contract deployment

- src/neo2/BlockchainOperations.cs
RunBlockchainAsync creates a named mutex so that `checkpoint create` command can detect if neo-express is running or not. However, since RunBlockchainAsync was not an async method, the mutex was getting disposed immediately. This PR updates RunBlockchainAsync (and RunCheckpointAsync for consistency) to be async methods so that mutex isn't disposed until chain shutdown
> Make RunBlockchainAsync async to fix online checkpoint mutex

- .vscode/tasks.json
- src/neo-express/Commands/ContractCommand.Invoke.cs
- src/neo-express/default.neo-express.json
- src/neo-express/neo-express.csproj
- src/neo2/BlockchainOperations.cs
- src/neo2/Extensions.cs
- src/neo2/Models/InvokeResponse.cs
- src/neo2/NeoRpcClient.cs
- src/neo2/RpcTransactionManager.cs
This PR adds `contract invoke` command to master. Unlike the contact invoke command implementation from the 1.0 release, this implementation has the contract invocation details (hash code + contract parameters) in a json file instead of passed on the command line. This json file can be checked into source control, supports arbitrarily complex contract parameters (including arrays and maps) and eventualy be generated by Visual DevTracker
Fixes #52
> Add contract invoke command

- src/neo2/BlockchainOperations.cs
contract param w/ specified string type should not be decoded as Hash160 or ByteArray
> Fix ParseContractParamObject decoding bug

- src/neo3/BlockchainOperations.cs
- src/neo3/ContractParameterParser.cs
This PR adds support for multi call invoke files. Template NEP-5 contract `mint` operation expects tx to invoke one or more NEO or GAS transfers before invoking the `mint` operation. This change allows contract neo-invoke file to have either a single contract call object or an array of contract call objects.
PR also adds support for `#` strings to be treated as Hash160/256 parameters
> Multi Contract call support in .neo-invoke.json files

- .vscode/settings.json
- src/neo3/BlockchainOperations.cs
- src/neo3/Extensions.cs
- src/nxp3/Commands/ContractCommand.Invoke.cs
- src/nxp3/nxp3.csproj
In some cases, `invokescript` RPC endpoint [reports an incorrect GAS amount](https://github.com/neo-project/neo/issues/1882). This leads to a scenario where neo express can't invoke a contract.
This PR adds a new `--gas` (or `-g`) command option to `contract invoke` to add the specified amount of gas to the SystemFee calculated by `invokescript`
> add --gas option to contract invoke

- src/nxp3/Commands/CheckpointCommand.Create.cs
- src/nxp3/Commands/CheckpointCommand.Restore.cs
- src/nxp3/Commands/CheckpointCommand.Run.cs
- src/nxp3/Commands/CheckpointCommand.cs
- src/nxp3/Commands/ContractCommand.Deploy.cs
- src/nxp3/Commands/ContractCommand.Get.cs
- src/nxp3/Commands/ContractCommand.Invoke.cs
- src/nxp3/Commands/ContractCommand.List.cs
- src/nxp3/Commands/ContractCommand.Storage.cs
- src/nxp3/Commands/ContractCommand.cs
- src/nxp3/Commands/CreateCommand.cs
- src/nxp3/Commands/ResetCommand.cs
- src/nxp3/Commands/RunCommand.cs
- src/nxp3/Commands/ShowCommand.Balance.cs
- src/nxp3/Commands/ShowCommand.Block.cs
- src/nxp3/Commands/ShowCommand.Transaction.cs
- src/nxp3/Commands/ShowCommand.cs
- src/nxp3/Commands/TransferCommand.cs
- src/nxp3/Commands/WalletCommand.Create.cs
- src/nxp3/Commands/WalletCommand.List.cs
- src/nxp3/Commands/WalletCommand.cs
- src/nxp3/Program.cs
* Remove `app.ShowHelp()` calls except for commands w/o subcommands (example: `checkpoint` without `create`, `restore` or `run`)
* Explicitly disable pager (via `app.ShowHelp(false)`) when showing help
* Specify `UsePagerForHelpText = false` on root command attribute
> disable help pager

- src/neo3/BlockchainOperations.cs
- src/neo3/Models/Nep17Contract.cs
- src/neo3/Node/ExpressApplicationEngine.cs
- src/neo3/Node/ExpressApplicationEngineProvider.cs
- src/neo3/Node/ExpressOracle.cs
- src/neo3/Node/ExpressRpcServer.cs
- src/neo3/Node/IExpressNode.cs
- src/neo3/Node/ITraceDebugSink.cs
- src/neo3/Node/LogPlugin.cs
- src/neo3/Node/OfflineNode.cs
- src/neo3/Node/OnlineNode.cs
- src/neo3/Node/TraceDebugSink.cs
- src/neo3/neo3.csproj
- src/nxp3/Commands/ContractCommand.Deploy.cs
- src/nxp3/Commands/ContractCommand.Invoke.cs
- src/nxp3/Commands/ContractCommand.List.cs
- src/nxp3/Commands/OracleCommand.Enable.cs
- src/nxp3/Commands/OracleCommand.Response.cs
- src/nxp3/Commands/TransferCommand.cs
This PR adapts Neo Express to changes introduced by https://github.com/neo-project/neo/pull/2044 (plus a few other recent changes)
* include script hash identification in `ListContractsAsync` and `ExpressListContracts` response
* include contract name (if available) in notify/log records + script hash and script identification in trace records
* Rename Nep5 operations/type to Nep17
* add `--json` option to several commands to produce machine readable output
> Adapt to Script Hash Identification Change

- .github/workflows/release.yml
- eng/azure-ci.yml
- src/neoxp/Commands/ContractCommand.Invoke.cs
- src/neoxp/Extensions/Extensions.cs
- src/neoxp/IExpressNode.cs
- src/neoxp/ITransactionExecutor.cs
- src/neoxp/Node/OfflineNode.cs
- src/neoxp/Node/OnlineNode.cs
- src/neoxp/TransactionExecutor.cs
- src/neoxp/neoxp.csproj
Fixes #146
This PR plumbs `contract invoke` Account and WitnessScope arguments thru when using `--results`. 
This enables contracts that use `(Transaction)Runtime.ScriptContainer` to be supported in `--results` operations
> contract invoke --results needs a mechanism to specify signers

- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/ContractCommand.Invoke.cs
- src/neoxp/Commands/ContractCommand.Run.cs
- src/neoxp/Commands/ContractCommand.cs
- src/neoxp/ITransactionExecutor.cs
- src/neoxp/TransactionExecutor.cs
adds new `contract run` command that accepts contract id (name or hash), method and arguments on the command line.  `contract run` also supported for batch command
fixes #150
> Add contract run command

- docs/settings.md
- src/neoxp/ExpressChainManager.cs
* Add rpc.BindAddress setting
* fix rpc.MaxGasInvoke and rpc.MaxFee to be decimal values
* add docs for settings
fixes #164
> Enable remote access for JSON-RPC methods

- Directory.Build.props
- src/neoxp/Models/NotificationRecord.cs
- src/neoxp/neoxp.csproj
* Update to Neo RC4 version of bctk-lib
* adapted to minor breaking change in BinarySerializer.Deserialize
> Update for Neo RC4

- changelog.md
- docs/command-reference.md
- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/FastForwardCommand.cs
- src/neoxp/ExpressChainManager.cs
- src/neoxp/IExpressChainManager.cs
- src/neoxp/IExpressChainManagerFactory.cs
- src/neoxp/IExpressNode.cs
- src/neoxp/Node/OfflineNode.cs
- src/neoxp/Node/OnlineNode.cs
- src/neoxp/Program.cs
Add fastfwd command to neo express. Allows user to specify a number of empty blocks to mint. Useful for scenarios where a set amount of time must occur between contract operations. Only works when node is *not* running
Fixes #181
> add NeoExpress fast forward command

- src/neoxp/Commands/ShowCommand.Block.cs
- src/neoxp/Commands/ShowCommand.Transaction.cs
- src/neoxp/Extensions/Extensions.cs
Neo.IO.Json types use Utf8JsonWriter under the hood when converting to an indendent string. Utf8JsonWriter encodes the '+' character - which occurs often in base64 encoded values - as '\u002b' for safety purposes. For example, the Base64 string `EQwhA6cH9+Easavr58RUB5argP11jo0vKfyuGkk2fngG8v86EUGe0Nw6` gets encoded as `EQwhA6cH9\u002bEasavr58RUB5argP11jo0vKfyuGkk2fngG8v86EUGe0Nw6` by JObject.ToString
Escaping the '+' character is important when transporting JSON across the internet. It's not important when writing JSON to the console. 
This PR adds a WriteJson extension method that uses newtonsoft (which does not encode '+' characters as Utf8JsonWriter does) to write a Neo JSON object to the console. 
Note, this approach is also slightly more efficient as there is no need to generate the …
> Write block/tx/applog JSON to console using newtonsoft to avoid breaking base64 encoded values

- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/ContractCommand.Deploy.cs
- src/neoxp/Extensions/ExpressNodeExtensions.cs
- src/neoxp/TransactionExecutor.cs
Fixes #199
Note, the `contract deploy --data` option only supports simple binary contract parameters. For more complex data types, the developer needs to use an invoke file
> optional data parameter for deploy

- changelog.md
- src/neoxp/Commands/ShowCommand.Notifications.cs
- src/neoxp/Commands/ShowCommand.Transaction.cs
- src/neoxp/Commands/ShowCommand.cs
- src/neoxp/Extensions/Extensions.cs
- src/neoxp/IExpressNode.cs
- src/neoxp/Models/NotificationRecord.cs
- src/neoxp/Node/Modules/ExpressRpcMethods.cs
- src/neoxp/Node/Modules/PersistencePlugin.cs
- src/neoxp/Node/OfflineNode.cs
- src/neoxp/Node/OnlineNode.cs
- src/neoxp/TransactionExecutor.cs
Adds a new `show notifications` command that dumps notifications in reverse chrono order in JSON format. includes arguments to limit notifications by count, by contract and by event name.
Other changes
* `show tx` emits valid JSON. Previously it emitted tx and app log as separate JSON objects
* Standardized on StringComparison.OrdinalIgnoreCase
> Add show notification command

- src/neoxp/Extensions/SmartContractExtensions.cs
- src/neoxp/Models/TransferNotificationRecord.cs
- src/neoxp/Node/Modules/ExpressRpcMethods.cs
- src/neoxp/Node/Modules/PersistencePlugin.cs
- src/neoxp/Node/OfflineNode.cs
- src/neoxp/Node/OnlineNode.cs
fixes #220, cc @gsmachado
issue #220 is an edge case - `GetNep17Balances` returns no results for genesis account in a blockchain where there have been no transfers (such as right after reset). The production `TokenTracker` plugin has the same issue, but is not an issue since chains with `TokenTracker` plugin are not going to be reset to genesis like Express does.
To fix this, I changed GetNep17Balances to collect account balances for all NEP-17 contracts then filter out ones that have zero balance. This ensures that we get valid balances even if there are no Transfer notifications. Once we have a list of tokens + balances, GetNep17Balances searchs backwards thru notifications to find the most recent block with a transfer notification for the specified account/token. If no transfer …
> Fix Invalid GetNep17Balances results

- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/OracleCommand.Response.cs
fix #212
RequestId should have been declared as a ulong? instead of as a hasValue/value tuple. The hasValue/value patten leads to an option use like `oracle response --request-id:1` instead of `oracle response --request-id 1` 
Also added request id option to batch mode version of oracle response
> Fix Oracle Response RequestId parameter

- changelog.md
- readme.md
- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/ContractCommand.Download.cs
`contract download` option defaults to `None` if option is unspecified and defaults to `All` if option value is unspecified. fixes #237
Also changed `batch` command `contract download` `height` from argument to option in order to match non-batch version of `contract download` . Fixes #238
cc @ixje
> Fix contract download arg parsing

- src/worknet/Commands/CreateCommand.cs
- src/worknet/Utility.cs
emit properties to .neo-worknet file for compatibility with .neo-express. In particular
* 'magic` 
* 'address-version' 
* 'consensus-nodes'
> Note: this is preliminary work intended to unblock other work. In particular, only `SaveWorknetFile` has been updated. These fields are ignored by `LoadWorknetAsync`. Once the [blockchain toolkit library is moved over to this repo](https://github.com/ngdenterprise/neo-blockchaintoolkit-library/issues/81), we will unify file management code across express and worknet.
> .neo-worknet / .neo-express file compat

- changelog.md
- docs/command-reference.md
- src/neoxp/Commands/WalletCommand.List.cs
- src/neoxp/Extensions/ExpressNodeExtensions.cs
- src/neoxp/Extensions/Extensions.cs
A [WIF encoded](https://developer.bitcoin.org/devguide/wallets.html#wallet-import-format-wif) private key can be used to specify both signing accounts (such as a contract deployer or the transfer source account) and non-signing accounts (such as a transfer target account).
> Support WIF encoded private keys

- docs/command-reference.md
Close https://github.com/neo-project/neo-express/issues/250.
> add download doc.

- .gitignore
- src/neoxp/Extensions/ExpressNodeExtensions.cs
Reverts neo-project/neo-express#305
This is a big change. This breaks old batch files that have been developed by users.
Sorry 😢 
Ill see if i can get some unit tests going for `neo-express` as well to prevent things like this.
> Revert "Inconsistent account naming"

- src/neoxp/Commands/BatchCommand.cs
closes #284 
**Change Log**
- fixed batch script commands from pushing onto next command arguments
> Batch Script Command Pusing on Next Command Arguments

- src/neoxp/Extensions/FileSystemExtensions.cs
close https://github.com/neo-project/neo-express/issues/283
Can we store the blockchain file in the root directory of the program, like neo-cli, instead of store in AppData folder.
> Blockchain Storage Path

- src/neoxp/Commands/CreateCommand.cs
Closes #332 
**Change Log**
- Added sync policy on create command
> Use testnet/mainnet network configuration

- src/bctklib/Constants.cs
- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/CreateCommand.cs
- src/neoxp/Extensions/FileSystemExtensions.cs
- src/neoxp/TransactionExecutor.cs
**Change Log**
- Updated batch command to use ResolveFileName for new default path
- Fixed bug with ResolveFileName; not adding extension
- Added default policy filename
- Removed policy sync on create command
- Fixed bug with sync not being used in batch files
- Changed sync resolve path for default policy and to resolve to global directory
- Added defaults for `setup.batch`  on create command
Directory `%userprofile%\.neo-express` defaults
**Example content**
```
checkpoint create checkpoints/init-blockchain -f
policy sync mainnet-policy genesis
checkpoint create checkpoints/policy-sync-mainnet -f
```
> Added default filenames and fixes

- version.json
This repo's release branch was produced by [nbgv-cli](https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/nbgv-cli.md) in the past, which need an admin permission to maintain.
Since we are using custom release branch now, I suggest that we should keep some rules same with the nbgv tool behaviour:
1. In `release/v*` branch, the version number should be only number and not contain any preview suffix, example: `3.6`,`3.7`.
2. In `master` branch, the version number should be the next release number with preview suffix, I suggest it change to `3.7-preview` for the moment.
When we want to create a production v3.6 release, we can merge `master` into `release/v3.6` then run release action on `release/v3.6`.
When we want to create a preview v3.7 release, we run release action on …
> Set release version to 3.6

- docs/quickstart.md
Updated 'transfer' command usage documentation in quickstart.md.
In the [following commit](https://github.com/neo-project/neo-express/pull/107/files#diff-69fb6c429d32f8d69e851da397e2c989118cc0b480892d742198d7dfd6331fab) the actual input order was modified, without docs being updated.
> Updated 'transfer' command usage documentation in quickstart.md

- docs/command-reference.md
- src/neoxp/Commands/ShowCommand.State.cs
- src/neoxp/Commands/ShowCommand.cs
```shell
> ./neoxp show state
Block height: 111
IsRunning: False
Config file: C:\Users\bitco\.neo-express\default.neo-express
```
```shell
> ./neoxp run
```
```shell
> ./neoxp show state
Block height: 112
IsRunning: True
Config file: C:\Users\bitco\.neo-express\default.neo-express
```
> Add method: show state

- .github/ISSUE_TEMPLATE/questions.md
- docs/quickstart.md
After some discussion, the documentation was changed back to docs.neo.org
> Modify the document link

- test/test.workflowvalidation/NeoxpAdvancedIntegrationTests.cs
- test/test.workflowvalidation/NeoxpToolIntegrationTests.cs
- test/test.workflowvalidation/RunCommand.cs
- test/test.workflowvalidation/WorkflowValidationTests.cs
The `RunCommand` class is created to avoid repeating code across the three test classes (`NeoxpAdvancedIntegrationTests`, `NeoxpToolIntegrationTests`, and `WorkflowValidationTests`).
An Argument List is used for the case of executing neoxp. 
Additionally, some code readability improvements are made.
> Refactor RunCommand to avoid code duplication in test classes

- src/bctklib/persistence/RpcClientExtensions.cs
Some `StateService` versions return `RpcException` with the message “Unknown storage item” when a key is not present in the state tree. Our `GetProvenState` only handled `KeyNotFound` and an older “Unknown value” variant, letting “Unknown storage item” bubble up and crash ApplicationEngine.Execute() during OnPersist
To fix it the error handling has been extended.
Merge after #490 
Related to #487
> Fix: Unknown storage item to null in GetProvenState

- src/build-tasks/build-tasks.csproj
- src/build-tasks/build/Neo.BuildTasks.targets
- src/collector/Utility/ZipStorer.cs
- src/collector/collector.csproj
- Add `.Net9` in `build-tasks` and `collector` projects and remove `.netStandard` & `.NETFramework`
- Get result to avoid `CA2022` warning in `Test01_FormatValidation`
> Add net9 and remove NetStandard&NetFramework

- extentions/neo3-visual-tracker/package.json
`bundle-nxp-download` is using a broken URI and version 3.7.6 instead of 3.8.2. It is adjusted so that the URI depends on the version and it downloads from NuGet instead of Git.
> Fix neo3-visual-tracker release download
