neo-project/neo-express

- src/neo-express/Extensions.cs
> fix GetAccount

- src/neo-express/Commands/ShowCommand.cs
- src/neo-express/neo-express.csproj
- src/neo2/Models/AccountBalance.cs
- src/neo2/Models/AccountResponse.cs
- src/neo2/Models/ClaimableResponse.cs
- src/neo2/Models/ClaimableTransaction.cs
- src/neo2/Models/UnclaimedResponse.cs
- src/neo2/Models/UnspentBalance.cs
- src/neo2/Models/UnspentTransaction.cs
- src/neo2/Models/UnspentsResponse.cs
> show command user friendly output + aliases

- src/neo-express/Program.cs
> set UsePagerForHelpText before calling UseDefaultConventions

- src/neo-express/BlockchainOperations.cs
- src/neo-express/Commands/CreateCommand.cs
- src/neo-express/Commands/RunCommand.cs
- src/neo-express/Extensions.cs
- src/neo-express/Models/DevWalletAccount.cs
- src/neo-express/Models/ExpressChain.cs
- src/neo-express/Node/NodeUtility.cs
move `--preload-gas` option from `run` command to `create` command.
fixes #44
> Preload on create, not run

- src/neo-express/Node/NodeUtility.cs
starting local node not needed for preload + causes deathPactException. 
fixes #50
> don't start node on preload

- src/neo2/RpcTransactionManager.cs
> sort conensus node accounts by public key before signing

- src/neo2/BlockchainOperations.cs
> Fix LoadInvocationFileJson

- src/neo3/BlockchainOperations.cs
- src/neo3/Node/ExpressAppLogsPlugin.cs
- src/neo3/Node/ExpressRpcServer.cs
- src/neo3/Node/NodeUtility.cs
- src/nxp3/Commands/ShowCommand.Transaction.cs
https://github.com/neo-project/neo-modules/tree/master/src/ApplicationLogs
Note, this is copy/pasted code. Current ApplicationLogs plugin is hardcoded to use LevelDB (https://github.com/neo-project/neo-modules/issues/204). Opened #72 to track replacing copy/pasted implemetnation w/ official plugin once it's been updated to support IStore
fixes #71
> Support ApplicationLogs plugin

- src/neo2/Node/NodeUtility.cs
transfer + claim preload transactions were not specifying witness. Fix that + call verify to ensure tx are valid before storing them in the block chanin
> verify preload tx

- src/neo3/BlockchainOperations.cs
- src/neo3/Extensions.cs
- src/neo3/Node/OfflineNode.cs
Blockchain.Singleton hangs forever if NeoSystem is not initialized. this PR initializes an offline node (which initializes NeoSystem) for a set of offline scenarios that access Blockchain.Singleton
> fix Blockchain.singleton offline hanging issue

- src/neo3/BlockchainOperations.cs
- src/neo3/Node/ExpressApplicationEngine.cs
- src/neo3/Node/ExpressRpcServer.cs
- src/neo3/Node/LogPlugin.cs
- src/neo3/Node/NodeUtility.cs
- src/neo3/Node/OfflineNode.cs
- src/neo3/neo3.csproj
This PR adapt neo-express to the new ManagementContract introduced in https://github.com/neo-project/neo/pull/2119. 
The only new functionality is opcode validation on contract deploy that was inspired by contract deploy logic in neo-cli
> ManagementContract Support

- src/neo3/Node/ExpressRpcServer.cs
Adds custom RPC endpoint that is like [standard getcontractstate endpoint](https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/getcontractstate.html) but that also supports retrieving contracts by name.
ExpressGetContractState supports three different parameter types:
* JSON number is converted to an int and matched against native contract IDs. If a match is found, a JSON object of the single native contract state is returned. If there is no match, it fall thru to be treated as a name
* serialized UInt160 string is converted to a Uint160 and retrieved via NativeContract.Management.GetContract. If a match is found, a JSON object of the single contract state is returned, If there is no match, an RpcException is thrown
* all other types are treated as strings and …
> ExpressGetContractState

- src/neoxp/Commands/ContractCommand.Storage.cs
Missed wiring up ContractCommand.Storage during recent cleanup and refactoring
fixes #97
> fix ContractCommand.Storage.OnExecuteAsync

- .github/workflows/release.yml
- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/ContractCommand.Deploy.cs
- src/neoxp/Commands/ContractCommand.Invoke.cs
- src/neoxp/ExpressNodeExtensions.cs
- src/neoxp/IExpressNode.cs
- src/neoxp/Node/OfflineNode.cs
- src/neoxp/Node/OnlineNode.cs
fixes #115
cc @csmuller @gsmachado
> add --witness-scope option to contract invoke + deploy

- .vscode/launch.json
- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/CheckpointCommand.Create.cs
- src/neoxp/Commands/ContractCommand.Deploy.cs
- src/neoxp/Commands/ContractCommand.Get.cs
- src/neoxp/Commands/ContractCommand.Storage.cs
- src/neoxp/Commands/OracleCommand.List.cs
- src/neoxp/Commands/ShowCommand.Balances.cs
- src/neoxp/ExpressChainManager.cs
- src/neoxp/ExpressNodeExtensions.cs
- src/neoxp/Extensions.cs
- src/neoxp/IExpressChainManager.cs
- src/neoxp/IExpressNode.cs
- src/neoxp/Node/ExpressOracle.cs
- src/neoxp/Node/OfflineNode.cs
- src/neoxp/Node/OnlineNode.cs
- src/neoxp/neoxp.csproj
> Gracefully handle multiple contracts w/ same name in contract storage

- src/neoxp/Node/ExpressApplicationEngine.cs
- src/neoxp/Node/ITraceDebugSink.cs
- src/neoxp/Node/TraceDebugSink.cs
- src/neoxp/neoxp.csproj
> add ProtocolSettings to trace

- src/neoxp/Commands/ContractCommand.Invoke.cs
- src/neoxp/Extensions/ExpressChainExtensions.cs
> Contract invoke should check to ensure either account or --results is specified

- src/neoxp/Node/ExpressApplicationEngine.cs
- src/neoxp/Node/ITraceDebugSink.cs
- src/neoxp/Node/TraceDebugSink.cs
- src/neoxp/neoxp.csproj
* Capture gas consumed on trace
* adapt to `Func<ExecutionContext, UInt160> getScriptIdentifier` param on `TraceRecord.Write`
> Adapt to Trace Model Changes in lib-bctk

- src/neoxp/Commands/StopCommand.cs
- src/neoxp/ExpressChainManager.cs
- src/neoxp/IExpressChainManager.cs
- src/neoxp/Node/ExpressRpcServer.cs
- src/neoxp/Program.cs
> Add STOP command

- src/neoxp/EventWrapper.cs
- src/neoxp/ExpressChainManager.cs
> Log fault tx message when running

- src/neoxp/Commands/BatchCommand.cs
> Add checkpoint reset support to batch command

- src/neoxp/Commands/ContractCommand.Invoke.cs
- src/neoxp/Commands/ContractCommand.Run.cs
- src/neoxp/ITransactionExecutor.cs
- src/neoxp/TransactionExecutor.cs
> Pass AdditionalGas option value to ContractInvokeAsync in contract run + invoke

- changelog.md
- src/neoxp/Node/ExpressOracle.cs
> fix oracle response exception text

- changelog.md
- docs/command-reference.md
- src/Directory.Build.props
- src/neoxp/Commands/ContractCommand.Deploy.cs
- src/neoxp/Commands/OracleCommand.Response.cs
- src/neoxp/Node/OfflineNode.cs
- src/neoxp/neoxp.csproj
fixes #189
fixes #186
fixes #183
> Fix large script execution

- .vscode/tasks.json
- changelog.md
- docs/settings.md
- src/neoxp/ExpressChainManager.cs
> Add rpc.MaxIteratorResultItems setting

- changelog.md
- src/neoxp/Program.cs
> unknown command has no exception handler

- src/neoxp/Commands/WalletCommand.List.cs
* include genesis account info
* modified `--json` output to be easier for script parsing
> wallet list updates

- src/neoxp/Commands/CreateCommand.cs
Fixes #218
(this is trivial so I'm going to merge w/o review as soon as it completes the build)
> Inconsistent "Default" help text

- changelog.md
- docs/settings.md
- src/neoxp/ExpressChainManager.cs
* RpcServer iterator session support enabled by default
* added `rpc.SessionEnabled` setting
> RPC Server Session support 

- changelog.md
- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/TransferCommand.cs
- src/neoxp/Extensions/ExpressNodeExtensions.cs
- src/neoxp/TransactionExecutor.cs
> Add optional data parameter to transfer

- changelog.md
- src/neoxp/Commands/ShowCommand.Balance.cs
- src/neoxp/Commands/ShowCommand.Balances.cs
- src/neoxp/Extensions/ExpressNodeExtensions.cs
- src/neoxp/TransactionExecutor.cs
> enable transfer to contract via `#` prefix

- changelog.md
- src/neoxp/Extensions/SmartContractExtensions.cs
- src/neoxp/Models/Nep17Contract.cs
- src/neoxp/Node/Modules/ExpressRpcServerPlugin.cs
> Add name, symbol and decimals properties to NEP11/17 GetBalances RPC methods as per changes to official tracker implementation

- .github/workflows/pack.yml
- neo-express.sln
- src/Directory.Build.props
Fixed dependencies (BlockchainToolkitLibraryVersion) and add solution file
> Fixed dependencies and add solution file

- src/neoxp/Program.cs
- src/neoxp/Properties/launchSettings.json
> fixes issue #298

- src/neoxp/Commands/ContractCommand.Download.cs
> Fixed wording for contract download height

- .gitignore
- src/neoxp/Extensions/ExpressNodeExtensions.cs
> Inconsistent account naming

- src/neoxp/Node/Modules/ExpressRpcServerPlugin.cs
> getapplicationlog response differs from neo-cli

- src/neoxp/TransactionExecutor.cs
> Fixed Json parameters for contract run command

- src/neoxp/Commands/CreateCommand.cs
- src/neoxp/Commands/WalletCommand.Create.cs
- src/neoxp/ExpressChainManagerFactory.cs
- src/neoxp/Properties/launchSettings.json
> wallet create with deterministic private key

- NuGet.Config
- neo-express.sln
> add nuget source

- src/neoxp/Extensions/ExpressNodeExtensions.cs
closes #254 
`neoxp transfer all NEO genesis NbGJ2PMcd7DeVYCnAf3neEuEqgLdaGX6rP` works now
> issues transferring genesis funds

- src/neoxp/Extensions/ExpressNodeExtensions.cs
- src/neoxp/Extensions/Extensions.cs
Close https://github.com/neo-project/neo-express/issues/272.
Support auto select last one of same named contracts, won't throw exception to stop the process.
Influence commands: 
- contract deploy: `data` parameter
- contract update: `contract` parameter
- contract run: all parameter
- contract invoke: all parameter
- transfer: `data` parameter
> Optimize find contract by name

- src/neoxp/Commands/CreateCommand.cs
- src/neoxp/Extensions/FileSystemExtensions.cs
closes #273
**Change Log**
- Add default location to $HOME/.neo-express on linux or %UserProfile%\\.neo-express for default.neo-express
> Add support to a global Neo Express instance

- src/neoxp/Commands/BatchCommand.cs
Bug fix, related to #324 
**Change Log**
- Fixed problem with default.neo-express file not being found at home directory for batch command
> Related to #324 

- docs/command-reference.md
> Update `contract download` command description

- src/neoxp/Program.cs
Closes #320 
**Change Log***
- Removed command suggestions.
> neoxp help suggests help

- .github/workflows/release.yml
- src/neoxp/Commands/CreateCommand.cs
- src/neoxp/Commands/WalletCommand.Create.cs
Hopefully closes #297 now
**Change Log**
- Added WIF suuport for importing private key
> Import WIF

- src/neoxp/TransactionExecutor.cs
Closes #339
**Change Log**
- Added IteropInterface to display data in results for neo-vm
> Add Display Iterator Results for VM

- .github/workflows/pr.yml
- .github/workflows/push.yml
- .github/workflows/test.yml
**Change Log**
- Added test to push.yml and pr.yml
> Update Github Actions

- src/Directory.Build.props
- src/bctklib/bctklib.csproj
- src/neoxp/Commands/ShowCommand.NFT.cs
- src/neoxp/neoxp.csproj
- src/trace/neotrace.csproj
- src/worknet/neoworknet.csproj
- test/test.bctklib/test.bctklib.csproj
Updated all the projects dependencies.
Some we marked as vulnerable.
**Change Log**
- Updated vulnerable & package dependencies
- Changed `Authors` to `The Neo Project`
- Changed `NeoVersion` to `3.6.1`
> Updated vulnerable & package dependencies

- src/neoxp/Commands/BatchCommand.BatchFileCommands.cs
- src/neoxp/Commands/BatchCommand.cs
- src/neoxp/Commands/CreateCommand.cs
- src/neoxp/Commands/WalletCommand.Create.cs
- src/neoxp/ExpressChainManager.cs
Closes #297 - now completely
**Change Log**
- Added wallet create command to batch files
- Changed formatting and text for wallet create command
**Example `setup.batch`**
```
wallet create bob
transfer 10000 gas genesis bob
```
> Added wallet create to batch

- .github/workflows/code.yml
- test/Directory.Build.props
- test/test.bctklib/TraceDebugTests.cs
- test/test.bctklib/test.bctklib.csproj
**Change Log**
- Added file code.yml
> Added file code.yml

- .github/workflows/pack.yml
- .github/workflows/push.yml
- .github/workflows/release.yml
Updated github action to use  `bctklib` packages and uploads to azure and nuget
**Change Log**
- Added `bctklib` to `pack.yml`, `push.yml`, `release.yml`
> Update github action for `bctklib` package

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/code.yml
**Change log**
- Added github issue templates
- Added bug
- Added feature
> Added github issue templates

- .github/workflows/test.yml
> Added neo-express application test in actions

- .github/workflows/push.yml
> Update push.yml (#368)

- src/neoxp/TransactionExecutor.cs
Small change
I highlighted in orange only in the image to show what changed
> Fixed struct so it displays on results

- .github/workflows/pack.yml
added if statement to unnecessary steps and changed token from my-get from development branch to master branch
master doesnt have secrets for myget, it uses environment variables instead compared to development branch
> Fix environments (master/development)

- .github/workflows/code.yml
We have cron job that runs. So we won't be checking for changes in code files. Or else it won't run. If that is the case we can remove cron job.
> Fix code.yml

- .github/ISSUE_TEMPLATE/questions.md
> Small Typos

- src/assertions/assertions.csproj
- src/bctklib/bctklib.csproj
- src/collector/collector.csproj
- src/test-harness/test-harness.csproj
> Changed DebugType to Portable

- src/neoxp/Commands/ContractCommand.Update.cs
- src/neoxp/Extensions/ExpressNodeExtensions.cs
- src/neoxp/TransactionExecutor.cs
> Added Update with data parameter

- .github/workflows/release.yml
- global.json
> Ready Check for release

- NuGet.Config
- src/neoxp/Commands/CreateCommand.cs
- version.json
> Fixes batch file on create

- src/neoxp/Extensions/ContractManifestExtensions.cs
Fixed `NEP-11` contract validation
Closes #431
> `NEP-11` Validator Fix

- src/bctklib/ContractParameterParser.cs
- src/neoxp/Commands/ContractCommand.Storage.cs
- src/neoxp/IExpressNode.cs
- src/neoxp/Node/Modules/ExpressRpcServerPlugin.cs
- src/neoxp/Node/NodeUtility.cs
- src/neoxp/Node/OfflineNode.cs
- src/neoxp/Node/OnlineNode.cs
Also had to move `contract storage` to `contract storage get` because there are conflicts in the arguments with the new command
> New command: contract storage update

- src/neoxp/ExpressChainManagerFactory.cs
- src/neoxp/Extensions/FileSystemExtensions.cs
> Fix: Relative paths not working properly when creating checkpoints #437

- docs/quickstart-old.md
- docs/quickstart.md
The original quickstart.md is very outdated, so I've rewritten a copy of it
> new quickstart.md

- src/neoxp/Extensions/ContractManifestExtensions.cs
- src/neoxp/TransactionExecutor.cs
close https://github.com/neo-project/neo-express/issues/429
Added: output detailed error message when compatibility check fails
Add: Add compatibility check for NEP-24, NEP-26, NEP-27.
> [fixedbug] nep-validation

- test/test.workflowvalidation/NeoxpAdvancedIntegrationTests.cs
- test/test.workflowvalidation/NeoxpToolIntegrationTests.cs
- test/test.workflowvalidation/WorkflowValidationTests.cs
Improve `RunDotNetCommand` to use `ProcessStartInfo.ArgumentList` instead of passing a single arguments string.  
This change improves robustness and allows correct handling of paths or arguments that contain spaces.
> Improve RunDotNetCommand to use Argument List

- src/bctklib/persistence/ICacheClient.cs
- src/bctklib/persistence/ICacheSnapshot.cs
- src/bctklib/persistence/StateServiceStore.cs
- Create a file per interface (`ICacheClient` & `ICacheSnapshot`)
- Use of throw-helper method
- Add `[NotNullWhen(true)]` to help the compiler and analyzers understand that value will not be null when the method returns true
- Styles
> Improve StateServiceStore

- src/bctklib/persistence/CheckpointStore.cs
- src/bctklib/persistence/MemoryTrackingStore.Snapshot.cs
- src/bctklib/persistence/PersistentTrackingStore.Snapshot.cs
- src/bctklib/persistence/PersistentTrackingStore.cs
- src/bctklib/persistence/RocksDbStore.Snapshot.cs
- src/bctklib/persistence/RocksDbStore.cs
- src/build-tasks/NeoContractInterface.cs
- src/collector/CodeCoverageCollector.cs
- src/collector/Models/NeoDebugInfo.cs
- src/neoxp/TransactionExecutor.cs
- Removing some warnings adding nullable attributes
- Adding some controls
> Remove some warnings
